### DISCUSSION TITLE
What Obsidian theme do you use?

### DISCUSSION THREAD

**Discussion by anutator** [KosmosisDire/obsidian-webpage-export#391] [Q&A] [answered]
What Obsidian theme do you use on your own site https://docs.obsidianweb.net/index.html ?
Is it possible to make files smaller? My html file is 3Mb in size or larger with different themes. But md file content is 100Kb only. Could it be smaller (maybe 1Mb) in size with css etc.?

How did you add grid with links to other pages to your home page?

**Comment by KosmosisDire** [comment, marked as answer]
1. I am using the Things theme.
2. Your files are so big because you are using the HTML Documents export mode. I have to embed all the styles, scripts, media, fonts, etc into every file. This is simply the size of the file with all that included. I am always trying to decrease this size but there isn't much I can do about it without causing some content to break. If you are hosting your files on a web server you can use Online Web Server export mode which will give you much much smaller files (close to the size of your markdown files). However these files must be hosted on a web server.
3. See #379

**Comment by anutator** [comment]
I use Things theme now. I think that you made some changes.

I checked files after Export as HTML - Online Web Server.
1.5 Mb — fonts, .ttf or .woff2, for example Source Code Pro — several files for Bold, regular, italic etc.
 Is it possible to use fonts which we don't need to download or fonts from site?
For example:

```css
/* cyrillic */
@font-face {
  font-family: 'Ubuntu';
  font-style: italic;
  font-weight: 400;
  font-display: fallback;
  src: url(https://fonts.gstatic.com/s/ubuntu/v20/4iCu6KVjbNBYlgoKej7wl0mwFg.woff2) format('woff2');
  unicode-range: U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}


@font-face /* 4 */ {
  font-family: MJXTEX-MI;
  src: url("https://cdn.jsdelivr.net/npm/mathjax@3/es5/output/chtml/fonts/woff-v2/MathJax_Main-Italic.woff") format("woff");
}
```
SFMono-Regular,Consolas,Menlo,monospace, Ubuntu Mono.

search-index.json — why this file is created? I've unchecked "Search bar" in plugin properties.
