### ISSUE TITLE
Export setup configuration files

### ISSUE THREAD

**Issue by hberge** [KosmosisDire/obsidian-webpage-export#306]
When a multi-file export requires unique settings for some files, or if you have multiple separate export-projects in the same vault, it would be great to have export configuration files. The format could for example be YAML. 

As a minimal example I have some files with very wide and long tables, so I might want that page to be as wide as possible, or maybe even override the css that causes that. 

```yaml
export-match-pattern-style: regex
export:
  - doc/.*\.md
  - big_table.md:
      content-width: 100%
```

This approach can be made very flexible and it might work well with command-line execution (#49).
