### ISSUE TITLE
Difference in page element structure relevance to CSS selectors

### ISSUE THREAD

**Issue by hberge** [KosmosisDire/obsidian-webpage-export#307]
Following the discussion in #306 I attempted to set a native obsidian "cssclasses" property on the web. Here I wanted to override the overflow-x: auto style property on certain <div> elements so I could display the full width of some wide tables without the need to scroll.

The class was set with this property section:
```
---
cssclass: "wide-tables"
---
```

This sets the class wide-tables on the main element, but there were div elements in the HTML that contain a `style="overflow-x: auto;"` property, which I needed to override. I didn't find a smart way to select these.

In obsidian the following css worked.

```css
div.wide-tables > div > div {
	overflow-x:visible!important;
}
```

However after export the structure of the webpage changed so I needed to change my selector to the following:

```css
div.wide-tables > div > div > div > div {
	overflow-x:visible!important;
}
```

I am thinking the `style="overflow-x: auto;"` property is unfortunate in the Obsidian html, so the best course of action might be to ask Obsidian to change this to a CSS controlled class with a variable.

The good news is that `cssclasses` itself worked without any problems.

**Comment by KosmosisDire** [comment]
Hmm, I think for the moment your work around is probably what I will stick with. I doubt the obsidian team will want to move those css declarations into classes because, like you said, they are not applied to any specific type of element that's easily selectable. And adding a class rule just for a single overflow declaration is a little bit weird. Additionally, this is only a problem for my plugin so they don't have much incentive to change it. I'll look into ways I could improve this though.

**Comment by KosmosisDire** [comment]
@hberge A better solution here would be to use an attribute selector which filters out only the elements having this style. You can do:

```css
div.wide-tables div[style='overflow-x: auto;'] 
{
	overflow-x: visible !important;
}
```

Which will work in both obsidian and the website.
