### ISSUE TITLE
The CSS background styling of the exported HTML differs from the preview styling in Obsidian.

### ISSUE THREAD

**Issue by Drean21** [KosmosisDire/obsidian-webpage-export#382]
This is the result after exporting.
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/49296233/f39c3662-b62e-4e7f-8f30-f5bb2677afe5)
When the background-color property is turned off, the displayed result is as follows, which matches the styling in Obsidian. (This is the styling I defined in Appearance - Code Snippets.)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/49296233/37b3fe32-f031-4c87-9a3b-5a36c6502715)

**Comment by KosmosisDire** [comment]
Can you give more detail about how you are export. Give me steps to reproduce the problem.

**Comment by Drean21** [comment]
> Owner

CSS snippet:
.markdown-source-view.mod-cm6 .cm-editor,
.markdown-reading-view {
    /* flex: 1 1 0;
    min-height: 0; */
    position: relative;
    background-color: #f4f4f4;
    /* Background color in light mode */
    /* Background color of notebook paper */
    background-image:
        linear-gradient(90deg, rgba(135, 206, 250, 0.3) 1px, transparent 1px),
        linear-gradient(rgba(211, 211, 211, 0.5) 1px, transparent 1px);
    background-size: 30px 30px;
    /* Size of grid lines */
    animation: wind 5s ease-in-out infinite alternate;
    /* Add animation effect */
}

/* Set transparent background when .theme-dark class is also present */
.theme-dark .markdown-source-view.mod-cm6 .cm-editor,
.theme-dark .markdown-reading-view {
    background-color: transparent;
}

@keyframes wind {
    0% {
        background-position: 0 0;
        /* Initial position */
    }

    100% {
        background-position: 30px 30px;
        /* Final position */
    }
}

**Comment by Drean21** [comment]
> Can you give more detail about how you are export. Give me steps to reproduce the problem.
> 
> Like what export mode you're using, what theme, etc

The export mode I'm using is "online web Service," and the theme is from https://github.com/colineckert/obsidian-things. Below is the custom CSS snippet I've defined.
```css
.markdown-source-view.mod-cm6 .cm-editor,
.markdown-reading-view {
    /* flex: 1 1 0;
    min-height: 0; */
    position: relative;
    background-color: #f4f4f4;
    /* Background color in light mode */
    /* Background color of notebook paper */
    background-image:
        linear-gradient(90deg, rgba(135, 206, 250, 0.3) 1px, transparent 1px),
        linear-gradient(rgba(211, 211, 211, 0.5) 1px, transparent 1px);
    background-size: 30px 30px;
    /* Size of grid lines */
    animation: wind 5s ease-in-out infinite alternate;
    /* Add animation effect */
}

/* Set transparent background when .theme-dark class is also present */
.theme-dark .markdown-source-view.mod-cm6 .cm-editor,
.theme-dark .markdown-reading-view {
    background-color: transparent;
}

@keyframes wind {
    0% {
        background-position: 0 0;
        /* Initial position */
    }

    100% {
        background-position: 30px 30px;
        /* Final position */
    }
}
```

**Comment by Drean21** [comment]
> Can you give more detail about how you are export. Give me steps to reproduce the problem.
> 
> Like what export mode you're using, what theme, etc

I found that adjusting the positioning of the CSS selectors resolved the issue with exporting using the plugin, and now the content displays correctly. Here's the modified CSS snippet:
```css
.theme-dark {
    --bg-color-notebook: #2a2825; /* Notebook background color for dark mode */
    --grid-notebook-line-color-1: #c7c7c71f; /* Grid line color 1 for dark mode */
    --grid-notebook-line-color-2: #74747440; /* Grid line color 2 for dark mode */
    --dotted-notebook-dot-color: #c7c7c71f; /* Dotted line dot color for dark mode */
}

.theme-light {
    --bg-color-notebook: #fef9f1; /* Notebook background color for light mode */
    --grid-notebook-line-color-1: #c7c7c740; /* Grid line color 1 for light mode */
    --grid-notebook-line-color-2: #afafaf40; /* Grid line color 2 for light mode */
    --dotted-notebook-dot-color: #c7c7c780; /* Dotted line dot color for light mode */
}

.markdown-source-view.mod-cm6 .cm-scroller,
.markdown-reading-view .markdown-rendered {
    /* flex: 1 1 0;
    min-height: 0; */
    position: relative;
    background-color: #f4f4f4; /* Background color for light mode */
    /* Background color of notebook paper */
    background-image:
        linear-gradient(90deg, rgba(135, 206, 250, 0.3) 1px, transparent 1px),
        linear-gradient(rgba(211, 211, 211, 0.5) 1px, transparent 1px);
    background-size: 30px 30px; /* Size of grid lines */
    animation: wind 5s ease-in-out infinite alternate; /* Add animation effect */
}

/* Set transparent background when .theme-dark class is also present */
.theme-dark .markdown-source-view.mod-cm6 .cm-scroller,
.theme-dark .markdown-reading-view .markdown-rendered {
    background-color: transparent;
}

@keyframes wind {
    0% {
        background-position: 0 0; /* Initial position */
    }

    100% {
        background-position: 30px 30px; /* Final position */
    }
}

```
