### ISSUE TITLE
[Bug]: Lists missing both numbers and bullets when inline LaTeX is present

### ISSUE THREAD

**Issue by Seudonym** [KosmosisDire/obsidian-webpage-export#489]
### What happened?

When a list point (both ordered and unordered) has inline latex in it, the bullet or number is not visible. 

Obsidian:
![image](https://github.com/user-attachments/assets/8be99745-9eaf-4bf8-a145-137e9463fc6b)

Exported:
![image](https://github.com/user-attachments/assets/a0dbf383-2779-4855-89b2-a4e2c1c21eef)

### Reproduction

Use inline latex in a list and export as "Online Website"

### Version

1.9.0

### Operating System

Arch Linux

### Obsidian Version

1.6.7

### Which browsers can you reproduce this in?

Chrome

### Relevant log output

```yaml
N/A
```

**Comment by KosmosisDire** [comment]
I think this has been reported before, if you could look up duplicates and make sure?

**Comment by Seudonym** [comment]
I could only find issues with latex rendering itself being broken. Nothing about latex affecting normal text or lists.

**Comment by Triveri** [comment]
I'm facing the same problem, both on 1.8.01 and 1.9.0-2b.

Obsidian:
![ObsidianReadingView](https://github.com/user-attachments/assets/f74513e3-0620-411a-b4f7-816d8dd3baef)

Exported:
![ExportedView](https://github.com/user-attachments/assets/a36d505d-58df-4bf8-b903-1030f8df6fd2)

`::marker` is there, but it doesn't appear, neither on Vivaldi or Firefox.
![ExportedViewInspector](https://github.com/user-attachments/assets/cd087e48-1daa-46bb-97f2-623de70730eb)

**Comment by RayhanHagel** [comment]
After playing a while with css, i found a work around to this problem. You need to add a css snippet with the code below

```css
.markdown-rendered ul{
    margin-block-start: -10px;
}

.list-collapse-indicator {
    display: none;
}

ul li::before {
	display: none;
}

ul li {
    padding-left: 0.5em;
}

ul li::marker {
    content: "•";
    color: currentColor;
    width: 1em;
}

li p {
    display: inline;
    margin: 0;
}
```

**Comment by Triveri** [comment]
Thank you! The snippet indeed worked around the problem.
Also, thanks to [this article](https://www.joshwcomeau.com/css/styling-ordered-lists-with-css-counters/) I was able to display correctly ordered lists as well by adding this to your snippet:

```css
ol li {
  counter-increment: olCounter;
}

ol li:before {
  content: counter(olCounter) ") ";
}

ol {
  list-style: none;
  counter-reset: olCounter;
}
```
