### ISSUE TITLE
Fix math styles sometimes not exporting correctly

### ISSUE THREAD

**Issue by dgudim** [KosmosisDire/obsidian-webpage-export#51]
It seems that after export all `mjx-math` tags get converted to `math` tags, this leads to 
1. This snippet not working in exports 
```css
mjx-math {
    font-size: 120% !important;
}
```
2. Weird paddings
![Screenshot_20230318_175247](https://user-images.githubusercontent.com/34401005/226116541-13b0e443-ac0e-41d8-bc1a-7c4b0fc12f8b.png)

I currently fix them with this snippet:
```css
math {
    font-size: 120% !important;
}

mjx-math {
    display: none !important;
}
```

![image](https://user-images.githubusercontent.com/34401005/226116693-4b671b98-90be-4296-a3c9-f13e9333cef8.png)
