### ISSUE TITLE
[Bug]: Admonitions (callouts) strange behavior

### ISSUE THREAD

**Issue by Chupakabra0** [KosmosisDire/obsidian-webpage-export#521]
### What happened?

1. Admonitions from plugin https://github.com/javalent/admonitions and callouts not support collapsibility (worked before)
2. Admonitions and callouts doesn't support custom .css snippets like this: https://github.com/r-u-s-h-i-k-e-s-h/Obsidian-CSS-Snippets/blob/Collection/Snippets/Callout%20styling%20-%20Old%20callouts.md (worked before).

### Reproduction

Just create note with admonition or callout (syntax style doesn't matter) and try to export it via any option to .html

### Last Working Version

1.8.1-2b

### Version

1.9.0-2b

### Operating System

Windows 11 Pro 23H2

### Obsidian Version

1.6.7 both

### Which browsers can you reproduce this in?

Firefox, Microsoft Edge

### Relevant log output

```yaml
N/A
```

### Additional Info

I don't have additional info about collapse, I don't strong enough in web stuff, but about snippets I have an idea: it seems to me plugin's style of `.callout-content` overrides my snippet's style, 'cause I able to remove `background-color` and `padding` via developer tools in Firefox and my snippet become working.

![not working image](https://github.com/user-attachments/assets/2e1bfdab-1bc1-4660-b346-dae849b1a79c)
![working image](https://github.com/user-attachments/assets/7ac95087-0886-4d11-a382-d8d641538734)

Temporary solution: rollback to 1.8.1-2b where snippets and collapse work as intended.

**Comment by KosmosisDire** [comment]
I'll check this out and try to make sure it works in the next release. Thanks!

**Comment by Chupakabra0** [comment]
1.9.0-3b update fixed callouts collapsability for me. But again, custom .css snippets doesn't work.

Used .css snippet:

```css
body {
    --callout-border-width: 0 0 0 4px;
    --callout-border-opacity: 1;
    --callout-radius: 0;
    --callout-padding: 0;
    --callout-title-padding: var(--size-4-4) var(--size-4-4);
    --callout-content-padding: var(--size-4-2) var(--size-4-4);
}

.admonition-bug, .admonition-note, .admonition-abstract .admonition-info
.admonition-tip, .admonition-success, .admonition-question, .admonition-warning,
.admonition-failure, .admonition-danger, .admonition-bug, .admonition-example,
.admonition-quote {
    page-break-inside: avoid !important;
}

.admonition-title-content .admonition-title-content {
    padding-left: 3px;
}

.admonition, .callout {
    page-break-inside: avoid !important;
}

.admonition-title-inner, .callout-title-inner {
    padding-left: 3px;
    color: var(--text-normal);
}

.admonition-content, .callout-content {
    background-color: var(--background-primary-alt);
    padding: 20px;
}

.admonition-title-icon, .svg-inline--fa {
    width: 18px;
    height: 18px;
}

div #webpage-icon {
    width: 0px;
    height: 0px;
}
```
