### ISSUE TITLE
[Bug]: Page title not updating

### ISSUE THREAD

**Issue by janncph** [KosmosisDire/obsidian-webpage-export#566]
### What happened?

Seems that the page title, shown in the browser title bar, is not updating (unless you manually reload the page). It keeps showing the title of the first page when you entered on the site.

### Reproduction

Click to another page via menu.

### Last Working Version

1.8.01

### Version

1.9.0-3b

### Operating System

WIN 11

### Obsidian Version

1.8.0

### Which browsers can you reproduce this in?

Chrome, Microsoft Edge

### Relevant log output

```yaml
Log:
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: deferred.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: main-styles.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: supported-plugins.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: global-variable-styles.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: theme.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: other-plugins.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: obsidian.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: snippets.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: mathjax.css"}
Progress	{"fraction":0,"message":"Filtering classes","subMessage":"..."}
Progress	{"fraction":0,"message":"Sorting classes","subMessage":"..."}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: mod-windows"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: is-frameless"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: is-hidden-frameless"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: is-focused"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: obsidian-app"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: theme-light"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: show-inline-title"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: show-ribbon"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: show-view-header"}
Progress	{"fraction":0,"message":"Cleanup classes","subMessage":"..."}
Progress	{"fraction":0,"message":"Filter duplicate classes","subMessage":"71 classes"}
Progress	{"fraction":0,"message":"Classes done","subMessage":"..."}
[INFO] No search-index.json exists. Creating new index.	{}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: deferred.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: main-styles.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: supported-plugins.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: global-variable-styles.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: theme.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: other-plugins.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: obsidian.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: snippets.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: mathjax.css"}
Progress	{"fraction":0,"message":"Filtering classes","subMessage":"..."}
Progress	{"fraction":0,"message":"Sorting classes","subMessage":"..."}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: mod-windows"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: is-frameless"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: is-hidden-frameless"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: obsidian-app"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: theme-light"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: show-inline-title"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: show-ribbon"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: show-view-header"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: is-focused"}
Progress	{"fraction":0,"message":"Cleanup classes","subMessage":"..."}
Progress	{"fraction":0,"message":"Filter duplicate classes","subMessage":"71 classes"}
Progress	{"fraction":0,"message":"Classes done","subMessage":"..."}
[INFO] No search-index.json exists. Creating new index.	{}


Settings:
{
  "settingsVersion": "0.0.0",
  "exportOptions": {
    "createDocumentContainer": true,
    "keepModHeaderFooter": false,
    "addPageIcon": true,
    "unifyTitleFormat": true,
    "createPusherElement": true,
    "makeHeadersTrees": true,
    "postProcess": true,
    "displayProgress": true,
    "inlineHTML": false,
    "exportPath": "C:\\Users\\jannk\\OneDrive\\Skrivebord\\html9",
    "addBodyClasses": true,
    "addMathjaxStyles": true,
    "addHeadTag": true,
    "backlinkOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Backlinks",
      "featurePlacement": {
        "selector": ".footer",
        "type": "start"
      }
    },
    "tagOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": ".header .data-bar",
        "type": "end"
      },
      "showInlineTags": true,
      "showFrontmatterTags": true
    },
    "aliasOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": ".header .data-bar",
        "type": "start"
      }
    },
    "propertiesOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Properties",
      "featurePlacement": {
        "selector": ".header",
        "type": "start"
      }
    },
    "fileNavigationOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "#left-sidebar-content",
        "type": "end"
      },
      "showCustomIcons": false,
      "showDefaultFolderIcons": false,
      "showDefaultFileIcons": false,
      "defaultFolderIcon": "lucide//folder",
      "defaultFileIcon": "lucide//file",
      "defaultMediaIcon": "lucide//file-image",
      "exposeStartingPath": true,
      "includePath": "site-lib/html/file-tree.html"
    },
    "searchOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Search...",
      "featurePlacement": {
        "selector": "#left-sidebar .topbar-content",
        "type": "start"
      }
    },
    "outlineOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Outline",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "end"
      },
      "startCollapsed": false,
      "minCollapseDepth": 0
    },
    "themeToggleOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "#right-sidebar .topbar-content",
        "type": "start"
      }
    },
    "graphViewOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Graph View",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "start"
      },
      "showOrphanNodes": true,
      "showAttachments": false,
      "allowGlobalGraph": true,
      "allowExpand": true,
      "attractionForce": 1,
      "linkLength": 30,
      "repulsionForce": 80,
      "centralForce": 2,
      "edgePruning": 100,
      "minNodeRadius": 3,
      "maxNodeRadius": 7
    },
    "sidebarOptions": {
      "enabled": true,
      "unavailable": false,
      "allowResizing": true,
      "allowCollapsing": true,
      "rightDefaultWidth": "20em",
      "leftDefaultWidth": "20em"
    },
    "customHeadOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "",
        "type": "end"
      },
      "sourcePath": "",
      "includePath": "site-lib/html/custom-head.html"
    },
    "documentOptions": {
      "enabled": true,
      "unavailable": false,
      "allowFoldingLists": true,
      "allowFoldingHeadings": true,
      "documentWidth": "40em"
    },
    "rssOptions": {
      "enabled": true,
      "unavailable": false,
      "siteUrl": "",
      "siteName": "",
      "authorName": ""
    },
    "relativeHeaderLinks": false,
    "includeJS": true,
    "includeCSS": true,
    "inlineMedia": false,
    "inlineCSS": false,
    "inlineJS": false,
    "inlineFonts": false,
    "inlineOther": false,
    "combineAsSingleFile": false,
    "offlineResources": false,
    "themeName": "",
    "slugifyPaths": true,
    "flattenExportPaths": false,
    "fixLinks": true,
    "faviconPath": "attachments\\logo-bynaturen.png",
    "iconEmojiStyle": "Native",
    "exportRoot": "",
    "includePluginCss": [],
    "includeStyleCssIds": [],
    "autoDisposeWebpages": true
  },
  "logLevel": "warning",
  "titleProperty": "title",
  "rssDateProperty": "date",
  "onlyExportModified": true,
  "deleteOldFiles": true,
  "exportPreset": "online",
  "openAfterExport": true,
  "filePickerBlacklist": [
    "(^|\\/)node_modules\\/",
    "(^|\\/)dist\\/",
    "(^|\\/)dist-ssr\\/",
    "(^|\\/)\\.vscode\\/"
  ],
  "filePickerWhitelist": [
    "\\.\\w+$"
  ]
}

Enabled Plugins:
	Editing Toolbar
	Webpage HTML Export
```
