### ISSUE TITLE
[Bug]: Linked, bundled PDF doesn’t open from Raw HTML outputs

### ISSUE THREAD

**Issue by mimcmillan** [KosmosisDire/obsidian-webpage-export#575]
### What happened?

A note has a link to a PDF document held in Obsidian in a container folder with the note. When the container folder is exported using Online Web Server mode, clicking this link opens the PDF document in the web browser in a new tab. (All good.)

Do the same thing using Raw HTML output, and now clicking the link in that webpage triggers an error, “This plugin is not supported”.

I recognize that many features will not work with Raw HTML mode. For example, headings do not collapse, in the page itself or in the Outline. (Correct me if that also is a bug! even for Raw mode.) I wonder though if it is not possible / easy to have the browser open the PDF? Since the PDF is present in the exported files so you just need a proper link to it.

Current workaround: go find the path to the exported PDF file after export (in your actual web server holding the Raw HTML output files) and enter that path into the Obsidian note as an external link, and export again (in Raw HTML mode). This works fine but the cumbersome workflow seems unnecessary.

### Reproduction

See above.

### Version

1.9.0-3b

### Operating System

Windows

### Obsidian Version

Current: v1.7.7;  installer: v1.6.3

### Which browsers can you reproduce this in?

Chrome, Microsoft Edge

### Relevant log output

```yaml
Settings:
{
  "settingsVersion": "0.0.0",
  "exportOptions": {
    "createDocumentContainer": true,
    "keepModHeaderFooter": false,
    "addPageIcon": true,
    "unifyTitleFormat": true,
    "createPusherElement": true,
    "makeHeadersTrees": true,
    "postProcess": true,
    "displayProgress": true,
    "inlineHTML": true,
    "exportPath": "C:\\Users\\mcmil\\OneDrive\\Desktop\\HTML-outputs-2",
    "addBodyClasses": true,
    "addMathjaxStyles": true,
    "addHeadTag": true,
    "backlinkOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "Backlinks",
      "featurePlacement": {
        "selector": ".footer",
        "type": "start"
      }
    },
    "tagOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": ".header .data-bar",
        "type": "end"
      },
      "showInlineTags": true,
      "showFrontmatterTags": true
    },
    "aliasOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": ".header .data-bar",
        "type": "start"
      }
    },
    "propertiesOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "Properties",
      "featurePlacement": {
        "selector": ".header",
        "type": "start"
      }
    },
    "fileNavigationOptions": {
      "enabled": false,
      "unavailable": true,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "#left-sidebar-content",
        "type": "end"
      },
      "showCustomIcons": false,
      "showDefaultFolderIcons": false,
      "showDefaultFileIcons": false,
      "defaultFolderIcon": "lucide//folder",
      "defaultFileIcon": "lucide//file",
      "defaultMediaIcon": "lucide//file-image",
      "exposeStartingPath": true,
      "includePath": "site-lib/html/file-tree.html"
    },
    "searchOptions": {
      "enabled": false,
      "unavailable": true,
      "displayTitle": "Search...",
      "featurePlacement": {
        "selector": "#left-sidebar .topbar-content",
        "type": "start"
      }
    },
    "outlineOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Outline",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "end"
      },
      "startCollapsed": false,
      "minCollapseDepth": 0
    },
    "themeToggleOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "#right-sidebar .topbar-content",
        "type": "start"
      }
    },
    "graphViewOptions": {
      "enabled": false,
      "unavailable": true,
      "displayTitle": "Graph View",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "start"
      },
      "showOrphanNodes": true,
      "showAttachments": false,
      "allowGlobalGraph": true,
      "allowExpand": true,
      "attractionForce": 1,
      "linkLength": 15,
      "repulsionForce": 80,
      "centralForce": 2,
      "edgePruning": 100,
      "minNodeRadius": 3,
      "maxNodeRadius": 7
    },
    "sidebarOptions": {
      "enabled": true,
      "unavailable": false,
      "allowResizing": true,
      "allowCollapsing": true,
      "rightDefaultWidth": "20em",
      "leftDefaultWidth": "20em"
    },
    "customHeadOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "head",
        "type": "end"
      },
      "sourcePath": "",
      "includePath": "site-lib/html/custom-head.html"
    },
    "documentOptions": {
      "enabled": true,
      "unavailable": false,
      "allowFoldingLists": true,
      "allowFoldingHeadings": true,
      "documentWidth": "40em"
    },
    "rssOptions": {
      "enabled": false,
      "unavailable": true,
      "siteUrl": "",
      "siteName": "xTensiv Vault",
      "authorName": ""
    },
    "relativeHeaderLinks": false,
    "includeJS": true,
    "includeCSS": true,
    "inlineMedia": true,
    "inlineCSS": true,
    "inlineJS": true,
    "inlineFonts": true,
    "inlineOther": true,
    "combineAsSingleFile": false,
    "offlineResources": false,
    "themeName": "",
    "slugifyPaths": false,
    "flattenExportPaths": false,
    "fixLinks": true,
    "faviconPath": "",
    "iconEmojiStyle": "Native",
    "exportRoot": "",
    "includePluginCss": [
      "obsidian-list-callouts",
      "callout-manager"
    ],
    "includeStyleCssIds": [],
    "autoDisposeWebpages": true
  },
  "logLevel": "warning",
  "titleProperty": "title",
  "rssDateProperty": "date",
  "onlyExportModified": true,
  "deleteOldFiles": true,
  "exportPreset": "raw-documents",
  "openAfterExport": false,
  "filePickerBlacklist": [
    "(^|\\/)node_modules\\/",
    "(^|\\/)dist\\/",
    "(^|\\/)dist-ssr\\/",
    "(^|\\/)\\.vscode\\/"
  ],
  "filePickerWhitelist": [
    "\\.\\w+$"
  ]
}

Enabled Plugins:
	Templater
	Advanced Cursors
	Advanced Tables
	Copy Block Link
	Homepage
	Linter
	PDF break page
	Quick Switcher++
	Recent Files
	Settings Search
	Style Settings
	Text Format
	Underline
	Creases
	List Callouts
	Quick Latex
	BRAT
	Callout Manager
	Better Export PDF
	Webpage HTML Export
```
