### ISSUE TITLE
[Bug]: Embedded “hidden” header is not hidden in the Outline

### ISSUE THREAD

**Issue by mimcmillan** [KosmosisDire/obsidian-webpage-export#576]
### What happened?

Say one note includes embeddings by headers from another note.

The first note includes CSS Class “hide-embedded-header”; and there is an active Snippet like this:
``` CSS
.hide-embedded-header .markdown-embed h3{
	display: none; 
}
```

In Obsidian, the first note does not show the hidden header in the document, nor does it show in the Outline.

In the plugin output website (Raw HTML output), the hidden header does not appear in the document (as expected), but it _does_ appear in the Outline, where it does _not_ function as a working link. (Clicking the hidden header does inject a new URL to that header, but the page does not jump there to where it is invisibly located.)

A related observation: in Obsidian, embedded headers never appear in the Outline of the note where they are embedded to, hidden or not.
So, I think the same bug can be described this way: the plugin output includes embedded headers in the Outline of the containing note’s webpage. This does not mimic Obsidian.

I guess it may be intentional, adding the embedded headers to the Outline, in which case the bug is (as initially stated) that at least the hidden embedded headers should not appear in the Outline, and if they must, then their links should take you to the right spot on the page.

### Reproduction

See above.

### Version

1.9.0-3b

### Operating System

Windows

### Obsidian Version

Current: v1.7.7;  installer: v1.6.3

### Which browsers can you reproduce this in?

Chrome, Microsoft Edge

### Relevant log output

```yaml
Settings:
{
  "settingsVersion": "0.0.0",
  "exportOptions": {
    "createDocumentContainer": true,
    "keepModHeaderFooter": false,
    "addPageIcon": true,
    "unifyTitleFormat": true,
    "createPusherElement": true,
    "makeHeadersTrees": true,
    "postProcess": true,
    "displayProgress": true,
    "inlineHTML": true,
    "exportPath": "C:\\Users\\mcmil\\OneDrive\\Desktop\\HTML-outputs-2",
    "addBodyClasses": true,
    "addMathjaxStyles": true,
    "addHeadTag": true,
    "backlinkOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "Backlinks",
      "featurePlacement": {
        "selector": ".footer",
        "type": "start"
      }
    },
    "tagOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": ".header .data-bar",
        "type": "end"
      },
      "showInlineTags": true,
      "showFrontmatterTags": true
    },
    "aliasOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": ".header .data-bar",
        "type": "start"
      }
    },
    "propertiesOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "Properties",
      "featurePlacement": {
        "selector": ".header",
        "type": "start"
      }
    },
    "fileNavigationOptions": {
      "enabled": false,
      "unavailable": true,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "#left-sidebar-content",
        "type": "end"
      },
      "showCustomIcons": false,
      "showDefaultFolderIcons": false,
      "showDefaultFileIcons": false,
      "defaultFolderIcon": "lucide//folder",
      "defaultFileIcon": "lucide//file",
      "defaultMediaIcon": "lucide//file-image",
      "exposeStartingPath": true,
      "includePath": "site-lib/html/file-tree.html"
    },
    "searchOptions": {
      "enabled": false,
      "unavailable": true,
      "displayTitle": "Search...",
      "featurePlacement": {
        "selector": "#left-sidebar .topbar-content",
        "type": "start"
      }
    },
    "outlineOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Outline",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "end"
      },
      "startCollapsed": false,
      "minCollapseDepth": 0
    },
    "themeToggleOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "#right-sidebar .topbar-content",
        "type": "start"
      }
    },
    "graphViewOptions": {
      "enabled": false,
      "unavailable": true,
      "displayTitle": "Graph View",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "start"
      },
      "showOrphanNodes": true,
      "showAttachments": false,
      "allowGlobalGraph": true,
      "allowExpand": true,
      "attractionForce": 1,
      "linkLength": 15,
      "repulsionForce": 80,
      "centralForce": 2,
      "edgePruning": 100,
      "minNodeRadius": 3,
      "maxNodeRadius": 7
    },
    "sidebarOptions": {
      "enabled": true,
      "unavailable": false,
      "allowResizing": true,
      "allowCollapsing": true,
      "rightDefaultWidth": "20em",
      "leftDefaultWidth": "20em"
    },
    "customHeadOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "head",
        "type": "end"
      },
      "sourcePath": "",
      "includePath": "site-lib/html/custom-head.html"
    },
    "documentOptions": {
      "enabled": true,
      "unavailable": false,
      "allowFoldingLists": true,
      "allowFoldingHeadings": true,
      "documentWidth": "40em"
    },
    "rssOptions": {
      "enabled": false,
      "unavailable": true,
      "siteUrl": "",
      "siteName": "xTensiv Vault",
      "authorName": ""
    },
    "relativeHeaderLinks": false,
    "includeJS": true,
    "includeCSS": true,
    "inlineMedia": true,
    "inlineCSS": true,
    "inlineJS": true,
    "inlineFonts": true,
    "inlineOther": true,
    "combineAsSingleFile": false,
    "offlineResources": false,
    "themeName": "",
    "slugifyPaths": false,
    "flattenExportPaths": false,
    "fixLinks": true,
    "faviconPath": "",
    "iconEmojiStyle": "Native",
    "exportRoot": "",
    "includePluginCss": [
      "obsidian-list-callouts",
      "callout-manager"
    ],
    "includeStyleCssIds": [],
    "autoDisposeWebpages": true
  },
  "logLevel": "warning",
  "titleProperty": "title",
  "rssDateProperty": "date",
  "onlyExportModified": true,
  "deleteOldFiles": true,
  "exportPreset": "raw-documents",
  "openAfterExport": false,
  "filePickerBlacklist": [
    "(^|\\/)node_modules\\/",
    "(^|\\/)dist\\/",
    "(^|\\/)dist-ssr\\/",
    "(^|\\/)\\.vscode\\/"
  ],
  "filePickerWhitelist": [
    "\\.\\w+$"
  ]
}

Enabled Plugins:
	Templater
	Advanced Cursors
	Advanced Tables
	Copy Block Link
	Homepage
	Linter
	PDF break page
	Quick Switcher++
	Recent Files
	Settings Search
	Style Settings
	Text Format
	Underline
	Creases
	List Callouts
	Quick Latex
	BRAT
	Callout Manager
	Better Export PDF
	Webpage HTML Export
```
