### ISSUE TITLE
[Bug]: popup preview doesn't work if a page has raw html at start.

### ISSUE THREAD

**Issue by soymadip** [KosmosisDire/obsidian-webpage-export#581]
### What happened?

if we have a page that has raw html at start of the page, the popup preview (the one that pops up when you hover over a link) shows blnk page. 

i have a page with this content: -
```html
<div align="center" style="padding-top:30vh;">
<br><br>
<h1> Methods are not yet documented.</h1>
<a href="https://soymadip.me/KireiSakura-Kit/faq.html#4._How_to_help_writing_docs?_0">Wanna help?</a>
</div>
```

now i tried to popup review in exported site & obisidian:-
(1st in website & then obsidian)

https://github.com/user-attachments/assets/c8fcc9f2-83e7-4f69-913c-b3ecf1686587

the popup comes blank in the website.

### Reproduction

1. write some raw html code in any page.
2. now in another page add an internal link to that page.
3. now in obsidian preview the link using ctrl/cmd + hover over the link. The popup will show the page preview.
4. now export both pages using extension. run webpage & hover over the internal link. (as a quich suggestion, it needs some improvements), popup will show. but the popup will be blank.

### Version

1.9.0--3b

### Operating System

Linux 6.12.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 18 Jan 2025 02:26:57 +0000 x86_64 GNU/Linux

### Obsidian Version

1.8.4

### Which browsers can you reproduce this in?

Firefox, Chrome, Microsoft Edge

### Relevant log output

```yaml
Log:
[INFO] 	Including stylesheet: css-settings-manager
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: deferred.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: main-styles.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: supported-plugins.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: global-variable-styles.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: theme.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: other-plugins.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: obsidian.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: snippets.css"}
Progress	{"fraction":0,"message":"Compiling css classes","subMessage":"Scanning: mathjax.css"}
Progress	{"fraction":0,"message":"Filtering classes","subMessage":"..."}
Progress	{"fraction":0,"message":"Sorting classes","subMessage":"..."}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: theme-dark"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: mod-linux"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: obsidian-app"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: show-ribbon"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: show-view-header"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: css-settings-manager"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: callout-style-customize"}
Progress	{"fraction":0,"message":"Collecting valid classes","subMessage":"Scanning: is-focused"}
Progress	{"fraction":0,"message":"Cleanup classes","subMessage":"..."}
Progress	{"fraction":0,"message":"Filter duplicate classes","subMessage":"53 classes"}
Progress	{"fraction":0,"message":"Classes done","subMessage":"..."}


Settings:
{
  "settingsVersion": "0.0.0",
  "exportOptions": {
    "createDocumentContainer": true,
    "keepModHeaderFooter": false,
    "addPageIcon": false,
    "unifyTitleFormat": true,
    "createPusherElement": true,
    "makeHeadersTrees": true,
    "postProcess": true,
    "displayProgress": true,
    "inlineHTML": false,
    "exportPath": "/home/soymadip/Documents/git/KireiSakura-Kit/docs",
    "addBodyClasses": true,
    "addMathjaxStyles": true,
    "addHeadTag": true,
    "backlinkOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Backlinks",
      "featurePlacement": {
        "selector": ".footer",
        "type": "start"
      }
    },
    "tagOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": ".header .data-bar",
        "type": "end"
      },
      "showInlineTags": true,
      "showFrontmatterTags": true
    },
    "aliasOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": ".header .data-bar",
        "type": "start"
      }
    },
    "propertiesOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Properties",
      "featurePlacement": {
        "selector": ".header",
        "type": "start"
      }
    },
    "fileNavigationOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "#left-sidebar-content",
        "type": "end"
      },
      "showCustomIcons": true,
      "showDefaultFolderIcons": false,
      "showDefaultFileIcons": false,
      "defaultFolderIcon": "lucide//folder",
      "defaultFileIcon": "lucide//file",
      "defaultMediaIcon": "lucide//file-image",
      "exposeStartingPath": false,
      "includePath": "site-lib/html/file-tree.html"
    },
    "searchOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Search Docs...",
      "featurePlacement": {
        "selector": "#left-sidebar .topbar-content",
        "type": "start"
      }
    },
    "outlineOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Outline",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "end"
      },
      "startCollapsed": false,
      "minCollapseDepth": "100"
    },
    "themeToggleOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "#right-sidebar .topbar-content",
        "type": "start"
      }
    },
    "graphViewOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Graph View",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "start"
      },
      "showOrphanNodes": true,
      "showAttachments": false,
      "allowGlobalGraph": true,
      "allowExpand": true,
      "attractionForce": 1,
      "linkLength": 15,
      "repulsionForce": 85,
      "centralForce": 2,
      "edgePruning": 100,
      "minNodeRadius": 3,
      "maxNodeRadius": 7
    },
    "sidebarOptions": {
      "enabled": true,
      "unavailable": false,
      "allowResizing": true,
      "allowCollapsing": true,
      "rightDefaultWidth": "19em",
      "leftDefaultWidth": "19em"
    },
    "customHeadOptions": {
      "enabled": false,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "head",
        "type": "end"
      },
      "sourcePath": "",
      "includePath": "site-lib/html/custom-head.html"
    },
    "documentOptions": {
      "enabled": true,
      "unavailable": false,
      "allowFoldingLists": true,
      "allowFoldingHeadings": true,
      "documentWidth": "43em"
    },
    "rssOptions": {
      "enabled": true,
      "unavailable": false,
      "siteUrl": "http://kireisakura.soymadip.me/",
      "siteName": "Docs | KireiSakura Kit",
      "authorName": "soymadip"
    },
    "relativeHeaderLinks": false,
    "includeJS": true,
    "includeCSS": true,
    "inlineMedia": false,
    "inlineCSS": false,
    "inlineJS": false,
    "inlineFonts": false,
    "inlineOther": false,
    "combineAsSingleFile": false,
    "offlineResources": false,
    "themeName": "",
    "slugifyPaths": true,
    "flattenExportPaths": false,
    "fixLinks": true,
    "faviconPath": "../icon.png",
    "iconEmojiStyle": "Native",
    "exportRoot": "",
    "includePluginCss": [],
    "includeStyleCssIds": [],
    "autoDisposeWebpages": true
  },
  "logLevel": "warning",
  "titleProperty": "title",
  "rssDateProperty": "date",
  "onlyExportModified": true,
  "deleteOldFiles": true,
  "exportPreset": "online",
  "openAfterExport": false,
  "filePickerBlacklist": [
    "(^|\\/)node_modules\\/",
    "(^|\\/)dist\\/",
    "(^|\\/)dist-ssr\\/",
    "(^|\\/)\\.vscode\\/"
  ],
  "filePickerWhitelist": [
    "\\.\\w+$"
  ]
}

Enabled Plugins:
	Style Settings
	Advanced Tables
	Webpage HTML Export
	Dataview
	BRAT
```
