### ISSUE TITLE
[Bug]: "value.replace is not a function" on startup

### ISSUE THREAD

**Issue by Drezil** [KosmosisDire/obsidian-webpage-export#585]
### What happened?

On Obsidian-startup/plugin-load i get a "value.replace is not a function". 

```
plugin:webpage-html-export:14166 Uncaught TypeError: value.replace is not a function
    at tidyAtRule (plugin:webpage-html-export:14166:20)
    at level1Optimize (plugin:webpage-html-export:18899:51)
    at optimize (plugin:webpage-html-export:26268:68)
    at eval (plugin:webpage-html-export:26254:33)
    at eval (plugin:webpage-html-export:25722:20)
    at loadOriginalSources (plugin:webpage-html-export:24742:121)
    at eval (plugin:webpage-html-export:25721:18)
    at applySourceMaps (plugin:webpage-html-export:24509:97)
    at Object.eval [as callback] (plugin:webpage-html-export:25720:16)
    at doInlineImports (plugin:webpage-html-export:25860:29)
```

This blocks startup until i disable the plugin. On reenabling it same error occurs and plugin-startup does not complete (i.e. the export-button in the side-menu is missing, etc.).

### Reproduction

In my vault (after installing & exporting yesterday):

- On Startup of obsidian, while all plugins are loading.
- On activation of the plugin

### Version

1.9.0-3b

### Operating System

Ubuntu

### Obsidian Version

Obsidian 1.8.4 / Installer 1.5.8

### Relevant log output

```yaml
Log:
[INFO] 	Including stylesheet: css-settings-manager
[INFO] 	Including stylesheet: svelte-pcimu8-style
[INFO] 	Including stylesheet: svelte-1vwr9dd-style
[INFO] 	Including stylesheet: svelte-156w7na-style
[INFO] 	Including stylesheet: svelte-egt0yd-style
[INFO] 	Including stylesheet: svelte-q3wqg9-style
[INFO] 	Including stylesheet: svelte-11adhly
[INFO] 	Including stylesheet: svelte-1widvzq-style
[INFO] 	Including stylesheet: svelte-1xm87ro
[INFO] 	Including stylesheet: svelte-hup5mn
[INFO] 	Including stylesheet: svelte-1wbh8tp
[INFO] 	Including stylesheet: svelte-deyewb


Settings:
{
  "settingsVersion": "0.0.0",
  "exportOptions": {
    "createDocumentContainer": true,
    "keepModHeaderFooter": false,
    "addPageIcon": true,
    "unifyTitleFormat": true,
    "createPusherElement": true,
    "makeHeadersTrees": true,
    "postProcess": true,
    "displayProgress": true,
    "inlineHTML": false,
    "exportPath": "/home/drezil/git/Obsidian-Export",
    "addBodyClasses": true,
    "addMathjaxStyles": true,
    "addHeadTag": true,
    "backlinkOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Backlinks",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "end"
      }
    },
    "tagOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": ".header .data-bar",
        "type": "end"
      },
      "showInlineTags": true,
      "showFrontmatterTags": true
    },
    "aliasOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": ".header .data-bar",
        "type": "start"
      }
    },
    "propertiesOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Properties",
      "featurePlacement": {
        "selector": ".header",
        "type": "start"
      }
    },
    "fileNavigationOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "#left-sidebar-content",
        "type": "end"
      },
      "showCustomIcons": true,
      "showDefaultFolderIcons": false,
      "showDefaultFileIcons": false,
      "defaultFolderIcon": "lucide//folder",
      "defaultFileIcon": "lucide//file",
      "defaultMediaIcon": "lucide//file-image",
      "exposeStartingPath": true,
      "includePath": "site-lib/html/file-tree.html"
    },
    "searchOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Search...",
      "featurePlacement": {
        "selector": "#left-sidebar .topbar-content",
        "type": "start"
      }
    },
    "outlineOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Outline",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "end"
      },
      "startCollapsed": false,
      "minCollapseDepth": 0
    },
    "themeToggleOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "#right-sidebar .topbar-content",
        "type": "start"
      }
    },
    "graphViewOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Graph View",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "start"
      },
      "showOrphanNodes": true,
      "showAttachments": false,
      "allowGlobalGraph": true,
      "allowExpand": true,
      "attractionForce": 1,
      "linkLength": 15,
      "repulsionForce": 80,
      "centralForce": 2,
      "edgePruning": 100,
      "minNodeRadius": 3,
      "maxNodeRadius": 7
    },
    "sidebarOptions": {
      "enabled": true,
      "unavailable": false,
      "allowResizing": true,
      "allowCollapsing": true,
      "rightDefaultWidth": "20em",
      "leftDefaultWidth": "20em"
    },
    "customHeadOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "head",
        "type": "end"
      },
      "sourcePath": "",
      "includePath": "site-lib/html/custom-head.html"
    },
    "documentOptions": {
      "enabled": true,
      "unavailable": false,
      "allowFoldingLists": true,
      "allowFoldingHeadings": true,
      "documentWidth": "80em"
    },
    "rssOptions": {
      "enabled": true,
      "unavailable": false,
      "siteUrl": "***",
      "siteName": "***",
      "authorName": "***"
    },
    "relativeHeaderLinks": true,
    "includeJS": true,
    "includeCSS": true,
    "inlineMedia": false,
    "inlineCSS": false,
    "inlineJS": false,
    "inlineFonts": false,
    "inlineOther": false,
    "combineAsSingleFile": false,
    "offlineResources": true,
    "themeName": "",
    "slugifyPaths": true,
    "flattenExportPaths": false,
    "fixLinks": true,
    "faviconPath": "",
    "iconEmojiStyle": "Native",
    "exportRoot": "",
    "includePluginCss": [
      "obsidian-citation-plugin",
      "dataview",
      "omnisearch",
      "obsidian-tasks-plugin",
      "obsidian-pretty-bibtex",
      "obsidian-pandoc-reference-list",
      "markwhen",
      "periodic-notes",
      "obsidian-projects",
      "folder-note-plugin",
      "obsidian-dynbedded",
      "supercharged-links-obsidian",
      "metadata-menu",
      "obsidian-tagfolder",
      "breadcrumbs",
      "cm-editor-syntax-highlight-obsidian",
      "pexels-banner",
      "svelte-hup5mn",
      "svelte-q3wqg9-style",
      "svelte-pcimu8-style",
      "svelte-1vwr9dd-style",
      "svelte-1xm87ro",
      "svelte-1wbh8tp",
      "svelte-4v6yoh",
      "svelte-11adhly",
      "svelte-156w7na-style",
      "svelte-egt0yd-style",
      "svelte-1widvzq-style",
      "svelte-deyewb"
    ],
    "includeStyleCssIds": [
      "obsidian-citation-plugin",
      "dataview",
      "omnisearch",
      "obsidian-tasks-plugin",
      "obsidian-pretty-bibtex",
      "obsidian-pandoc-reference-list",
      "markwhen",
      "periodic-notes",
      "obsidian-projects",
      "folder-note-plugin",
      "obsidian-dynbedded",
      "supercharged-links-obsidian",
      "metadata-menu",
      "obsidian-tagfolder",
      "breadcrumbs",
      "cm-editor-syntax-highlight-obsidian",
      "pexels-banner",
      "svelte-hup5mn",
      "svelte-q3wqg9-style",
      "svelte-pcimu8-style",
      "svelte-1vwr9dd-style",
      "svelte-1xm87ro",
      "svelte-1wbh8tp",
      "svelte-4v6yoh",
      "svelte-11adhly",
      "svelte-156w7na-style",
      "svelte-egt0yd-style",
      "svelte-1widvzq-style",
      "svelte-deyewb"
    ],
    "autoDisposeWebpages": true
  },
  "logLevel": "warning",
  "titleProperty": "title",
  "rssDateProperty": "date",
  "onlyExportModified": true,
  "deleteOldFiles": true,
  "exportPreset": "online",
  "openAfterExport": false,
  "filePickerBlacklist": [
    "(^|\\/)node_modules\\/",
    "(^|\\/)dist\\/",
    "(^|\\/)dist-ssr\\/",
    "(^|\\/)\\.vscode\\/"
  ],
  "filePickerWhitelist": [
    "\\.\\w+$"
  ]
}

Enabled Plugins:
	Auto Link Title
	Citations
	Dataview
	Omnisearch
	PlantUML
	Tasks
	Zotero Integration
	Graph Link Types
	Pretty BibTeX
	ReadItLater
	Pandoc Reference List
	Paste image rename
	Minimal Theme Settings
	Style Settings
	Gitlab Issues
	Markwhen
	Calendar
	Frontmatter Tag Suggest
	Periodic Notes
	Force note view mode
	Templater
	Linter
	BRAT
	Projects
	Folder Note
	Advanced Tables
	Git
	Dynbedded
	Supercharged Links
	Local Media Embedder
	Metadata Menu
	AI image analyzer
	Text Extractor
	TagFolder
	Breadcrumbs
	Editor Syntax Highlight
	Sync Graph Settings
	Pixel Banner
	Webpage HTML Export
```
