### ISSUE TITLE
[Bug]: Cannot locate the CSS selector

### ISSUE THREAD

**Issue by Ryanu9** [KosmosisDire/obsidian-webpage-export#592]
### What happened?

I want to add custom JS code to my webpage, but I can't locate #center-content .data-bar.

### Reproduction

this is my setting
![Image](https://github.com/user-attachments/assets/f5dd16b0-74ef-4c9d-8d60-fd426792c75d)

When I try to export, I get the following message:
Progress	{"fraction":0.12509216023593034,"message":"Building Webpages","subMessage":"24-渗透/HMV/22.DC03.md"}
[WARNING] 	Could not insert feature custom-head with placement: [object Object]
[INFO] 	Waiting for all sections to be counted...
[INFO] 	Waiting for transclusions to render...
[INFO] 	Waiting for generic plugins to render...

### Version

1.9.0-3b

### Operating System

windows 10

### Obsidian Version

1.8.9

### Relevant log output

```yaml
Progress	{"fraction":0.12509216023593034,"message":"Building Webpages","subMessage":"24-渗透/HMV/22.DC03.md"}
[WARNING] 	Could not insert feature custom-head with placement: [object Object]
[INFO] 	Waiting for all sections to be counted...
[INFO] 	Waiting for transclusions to render...
[INFO] 	Waiting for generic plugins to render...

Settings:
{
  "settingsVersion": "1.8.03",
  "exportOptions": {
    "createDocumentContainer": true,
    "keepModHeaderFooter": false,
    "addPageIcon": true,
    "unifyTitleFormat": true,
    "createPusherElement": true,
    "makeHeadersTrees": true,
    "postProcess": true,
    "displayProgress": true,
    "inlineHTML": false,
    "exportPath": "E:\\notes",
    "addBodyClasses": true,
    "addMathjaxStyles": true,
    "addHeadTag": true,
    "backlinkOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Backlinks",
      "featurePlacement": {
        "selector": ".footer",
        "type": "start"
      }
    },
    "tagOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": ".header .data-bar",
        "type": "end"
      },
      "showInlineTags": true,
      "showFrontmatterTags": true
    },
    "aliasOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "别名",
      "featurePlacement": {
        "selector": ".header .data-bar",
        "type": "end"
      }
    },
    "propertiesOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Properties",
      "featurePlacement": {
        "selector": ".header",
        "type": "start"
      }
    },
    "fileNavigationOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "#left-sidebar-content",
        "type": "end"
      },
      "showCustomIcons": false,
      "showDefaultFolderIcons": false,
      "showDefaultFileIcons": false,
      "defaultFolderIcon": "lucide//folder",
      "defaultFileIcon": "lucide//file",
      "defaultMediaIcon": "lucide//file-image",
      "exposeStartingPath": true,
      "includePath": "site-lib/html/file-tree.html"
    },
    "searchOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Search...",
      "featurePlacement": {
        "selector": "#left-sidebar .topbar-content",
        "type": "start"
      }
    },
    "outlineOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Outline",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "end"
      },
      "startCollapsed": false,
      "minCollapseDepth": 0
    },
    "themeToggleOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "",
      "featurePlacement": {
        "selector": "#right-sidebar .topbar-content",
        "type": "start"
      }
    },
    "graphViewOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "Graph View",
      "featurePlacement": {
        "selector": "#right-sidebar-content",
        "type": "start"
      },
      "showOrphanNodes": true,
      "showAttachments": false,
      "allowGlobalGraph": true,
      "allowExpand": true,
      "attractionForce": 2,
      "linkLength": 15,
      "repulsionForce": 80,
      "centralForce": 3,
      "edgePruning": 100,
      "minNodeRadius": 4,
      "maxNodeRadius": 8
    },
    "sidebarOptions": {
      "enabled": true,
      "unavailable": false,
      "allowResizing": true,
      "allowCollapsing": true,
      "rightDefaultWidth": "20em",
      "leftDefaultWidth": "20em"
    },
    "customHeadOptions": {
      "enabled": true,
      "unavailable": false,
      "displayTitle": "comments",
      "featurePlacement": {
        "selector": "#center-content .data-bar",
        "type": "end"
      },
      "sourcePath": "..\\1.html",
      "includePath": "site-lib/html/custom-head.html"
    },
    "documentOptions": {
      "enabled": true,
      "unavailable": false,
      "allowFoldingLists": true,
      "allowFoldingHeadings": true,
      "documentWidth": "50em"
    },
    "rssOptions": {
      "enabled": true,
      "unavailable": false,
      "siteUrl": "c1trus.top",
      "siteName": "c1trus's Notes",
      "authorName": "C1trus"
    },
    "relativeHeaderLinks": false,
    "includeJS": true,
    "includeCSS": true,
    "inlineMedia": false,
    "inlineCSS": false,
    "inlineJS": false,
    "inlineFonts": false,
    "inlineOther": false,
    "combineAsSingleFile": false,
    "offlineResources": false,
    "themeName": "",
    "slugifyPaths": true,
    "flattenExportPaths": false,
    "fixLinks": true,
    "faviconPath": "C:\\\\Users\\Administrator\\Pictures\\favicon_logosc\\favicon.png",
    "iconEmojiStyle": "Native",
    "exportRoot": "",
    "includePluginCss": [
      "title-stylesheet",
      "excalidraw-embedded-light",
      "excalidraw-embedded-dark",
      "dataview"
    ],
    "includeStyleCssIds": [],
    "autoDisposeWebpages": true
  },
  "logLevel": "warning",
  "titleProperty": "title",
  "rssDateProperty": "date",
  "onlyExportModified": true,
  "deleteOldFiles": false,
  "exportPreset": "online",
  "openAfterExport": false,
  "filePickerBlacklist": [
    "(^|\\/)node_modules\\/",
    "(^|\\/)dist\\/",
    "(^|\\/)dist-ssr\\/",
    "(^|\\/)\\.vscode\\/"
  ],
  "filePickerWhitelist": [
    "\\.\\w+$"
  ]
}

Enabled Plugins:
	Webpage HTML Export
	增强编辑
	Admonition
	AttachFlow
	Auto Link Title
	BRAT
	Commander
	Dataview
	Easy Typing
	Editing Toolbar
	Enhancing Mindmap
	File Explorer Note Count
	Excalidraw
	floating toc
	Hover Editor
	I18N
	Iconize
	Image auto upload
	Image Toolkit
	Linter
	Local Images Plus
	Number Headings
	Omnisearch
	Sortable
	Recent Files
	Style Settings
	Table Generator
	Templater
	Virtual Linker / Glossary
```
