### ISSUE TITLE
[Bug] [1.8.01]: Export content is broken on certain themes

### ISSUE THREAD

**Issue by CorentinRubio** [KosmosisDire/obsidian-webpage-export#603]
### What happened?

I use the [Obsidian Border Theme](https://github.com/Akifyss/obsidian-border), and the exports while using this theme result in a broken webpage where many of the css of the theme is written in plain text.

![Image](https://github.com/user-attachments/assets/843b15a4-4e16-4522-be61-9f2a5a9e9e9b)

Here is the link to the [theme.css](https://github.com/Akifyss/obsidian-border/blob/main/theme.css)

After digging a bit, I found that they use some icons that seems to be url encoded in UTF8 and for some reason the export can't handle them properly.

Here is an example of it, it's inside the `theme.css` of the theme :

```css
body:not(.new-tab-text-btn-restore) .workspace-leaf-content[data-type="empty"] .empty-state-action:nth-child(1):before {
    content: " ";
    display: block;
    height: 20px;
    width: 20px;
    background-color: var(--icon-color);
	-webkit-mask-image: url('data:image/svg+xml;utf8,<?xml version="1.0" encoding="UTF-8"?><svg id="svg0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><defs><style>.cls-1{fill:none;}</style></defs><path d="M15,19.17H3.33c-1.38,0-2.5-1.12-2.5-2.5V5c0-1.38,1.12-2.5,2.5-2.5h5.83c.46,0,.83,.37,.83,.83s-.37,.83-.83,.83H3.33c-.46,0-.83,.37-.83,.83v11.67c0,.46,.37,.83,.83,.83H15c.46,0,.83-.37,.83-.83v-5.83c0-.46,.37-.83,.83-.83s.83,.37,.83,.83v5.83c0,1.38-1.12,2.5-2.5,2.5Z"/><path d="M6.67,14.17c-.22,0-.43-.09-.59-.24-.21-.21-.29-.51-.22-.79l.83-3.33c.04-.15,.11-.28,.22-.39L14.83,1.49h0c1.01-1.01,2.66-1.01,3.68,0,.49,.49,.76,1.14,.76,1.84s-.27,1.35-.76,1.84l-7.92,7.92c-.11,.11-.24,.18-.39,.22l-3.33,.83c-.07,.02-.13,.03-.2,.03Zm1.59-3.74l-.44,1.76,1.76-.44,7.75-7.75c.18-.18,.27-.41,.27-.66s-.1-.48-.27-.66c-.36-.36-.96-.36-1.32,0l-7.75,7.75Z"/><rect class="cls-1" width="20" height="20"/></svg>');
}
```
Here it's the line `-webkit-mask-image` that crashes the export.

I removed all of the lines and the export works fine (simply commenting them with /* */ does not solve the issue)
The theme has 22 of theses properties, and I don't want to have missing icons randomly.

Not sure if it's easy to fix, or if anyone has had this issue before, not a lot of people uses the Border Theme with the export plugin probably.
But I still wanted to report the issue if it could happen with other themes that uses url encoded svg like theses.

### Reproduction

1. Create a new Obsidian Vault
2. Install the [Obsidian Border Theme](https://github.com/Akifyss/obsidian-border)
3. Install the HTML export plugin
4. Set the export as HTML Documents or Raw HTML Documents
5. Export

### Last Working Version

I did not test any other version other than 1.8.01

### Version

1.8.01

### Operating System

Windows

### Obsidian Version

1.8.9

### Relevant log output

```yaml
NA
```
